/todo:
  GET:
    routeFqdn: "https://stoplight.io/mocks/sonic-host/amplify-demo-todo/83730700"
  POST:
    routeFqdn: "https://stoplight.io/mocks/sonic-host/amplify-demo-todo/83730700"
    authorization:
      header: "Authorization"
      type: "jwt"
