/todo:
  get:
    routeFqdn: "https://stoplight.io/mocks/sonic-host/amplify-demo-todo/83730700"
    authorization:
      header: "Authorization"
      type: "jwt"
  post:
    routeFqdn: "https://stoplight.io/mocks/sonic-host/amplify-demo-todo/83730700"
    authorization:
      header: "Authorization"
      type: "jwt"
